---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  KotlinCourseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: chrisbarbours-kotlin-course
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'KotlinCourseBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'KotlinCourseBucket', /*]]