package app.content.overview

import Markdown
import react.RBuilder

val types: RBuilder.() -> Unit = {
    Markdown {
        attrs.source = """
                # Classes and Types
                ...
                ## Classes
                ...
                ## Data Classes
                ...
                ## Interfaces
                ...
                # Inheritance
                ...
                ## Kotlin Type Tree
                ...
                ## Nothing
                ...
                ## Generics
                ...
                ### Reified
                ...
                ## Enum Classes
                ...
                ## Objects and Companions (Singletons)
                ...
                ## Type Aliases
                ...
                ## Yada Yada Yada...
                """.trimIndent().trimMargin()
    }
}